### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by monza258** [kernie66/homebridge-pushcutter#1]
Hi, great plugin. Thank you. Is it possible to include a image option? Set a url to send some image with a notification.

**Comment by kernie66** [comment]
Hi, I'm glad you like it. Adding an image is a good idea, I will look into that.

Regards,
Kenneth

**Comment by monza258** [comment]
Hi, any news about it?

**Comment by kernie66** [comment]
Added in version 1.1.0.
