### ISSUE TITLE
OPTION REQUEST Switch as a Group

### ISSUE THREAD

**Issue by monza258** [kernie66/homebridge-pushcutter#2]
Is it possible to chance the Notification Switches as one Button? So like a switch group? 

Bevor i have use the Homebridge-messenger-plugin. It's really better when you use more switches for pushcut or pushcutter. 

![image](https://user-images.githubusercontent.com/37027557/135741183-3e44dc7f-1670-48de-93a8-69e484b988a1.jpeg)

**Comment by monza258** [comment]
Hi @kernie66, any chance to update it?

**Comment by monza258** [comment]
Hi @kernie66, no support anymore?

**Comment by kernie66** [comment]
Hi @monza258 

I did look into it, but I don't really see the benefit. I'm not sure how I would implement it, so for now I will leave it as it is.

**Comment by monza258** [comment]
Thanks for Reply. So what's the benefit. The benefit is that you have only one button as a group. Now I have for every Pushcut option one button in HomeKit. 

You didn't see how it works in the messenger plugin to implement it?

**Comment by monza258** [comment]
Hi @kernie66, do you have checked about the option to set the switches as a group?

**Comment by kernie66** [comment]
Yes, I did check the Messenger plugin, but it is written in a different way than my plugin so it was not that easy to understand how I would implement it. This is a learning experience for me, and unfortunately the switch group function is not a priority right now.

And I still don't see the benefit. I just have my Pushcut notifications in a separate "Notifications" room. Then it is easy to keep track of them, as I don't use the "turn off all notifications" feature that you can do with a switch group.

I hope this plugin still fulfills your needs. 

Regards,
Kenneth
