### ISSUE TITLE
Configuration not updating

### ISSUE THREAD

**Issue by antonkrall** [kernie66/homebridge-pushcutter#4]
When you first create a new notification, everything seems to work but then, lets say, I changed the configuration to a custom title and message, the logs show that its loading a cached resource and the title and message stays the same as when you originally created the notification, seems it alwars reads the cache instead of reloading the json config. 

If you need more info to debug the issue, please let me know. Thank you very much for your help and a great HB plugin, was exactly what I was looking for.

**Comment by kernie66** [comment]
Yes, that is an effect of the design that allows you to update the texts in e.g. scenes and using e.g. Eve, without loosing the updates when Homebridge restarts.

I think I need to add a parameter so you can set if you want the config file to be reloaded. I don't know if I can make it auto-detect that the config file has changed, but I will look into that.

**Comment by antonkrall** [comment]
Thanks

**Comment by kernie66** [comment]
I have checked the issue and have a solution. I will update the plugin as soon as possible.

**Comment by antonkrall** [comment]
Thanks

Slds / Regards

— Anton Krall
