### ISSUE TITLE
Installed, configured...no switch!

### ISSUE THREAD

**Issue by barryl93** [kernie66/homebridge-pushcutter#6]
I must be a flaming idiot... I have installed and configured Pushcutter, but I can't find the switch it's supposed to generate anywhere! I've tried restarting HB multiple times, looked in Home.app, Eve, Home+, and Controller for HomeKit. Help!

Here's my config...

`{
    "name": "Pushcutter",
    "api": {
        "selectApi": "secret",
        "apiCode": "[REDACTED]",
        "locale": "US"
    },
    "notifications": [
        {
            "switchName": "Water Sensor Battery",
            "notificationName": "Low Battery",
            "useWebhook": false,
            "mute": 5,
            "pcTitle": "Battery Warning!",
            "pcText": "The water sensor battery is low!",
            "startOnReboot": false,
            "sound": "default",
            "useConfig": true
        }
    ],
    "platform": "Pushcutter"
}`

**Comment by kernie66** [comment]
I can't see anything obviously wrong. But if you don't see the switch in your default room, it should mean that something went wrong in the initialisation. I haven't tested the 'secret' API version in a while, perhaps something is broken but I can't see that the code changed in that part.

Try to look in the log with e.g. 'cat /var/lib/homebridge/homebridge.log | grep [pP]ushcutter' when HB is restarted, it should tell you if something is not as expected. Ignore the version messages, they are not relevant. You should see the API URL, it should look like "api.pushcut.io/[your secret]/notifications" and then it should list your devices and notifications, if they can be accessed. The plugin prints a lot of useful information when it starts. Hopefully you will find where the problem starts, and either can correct them or notify me if there is an error in the plugin. 

Regards,
Kenneth

**Comment by barryl93** [comment]
Wow, thanks for the quick reply! Based on your comments, I went ahead and generated an API key and tried that instead of the webhook and it worked on the first try. So, thanks!!!

**Comment by kernie66** [comment]
I'm glad that it worked out for you. Maybe I need to clarify something in the docs, I'll take a look at that.
